# Build Stage
FROM node:20-alpine AS builder

ARG ELEVENLABS_API_KEY
ARG ELEVENLABS_VOICE_ID
ARG ELEVENLABS_MODEL_ID
ARG MEMU_API_KEY
ARG MEMU_USER_ID
ARG MEMU_AGENT_ID
ARG MEMU_BASE_URL
ARG SAM_API_URL
ARG SAM_API_KEY
ARG GEMINI_API_KEY
ARG ANIMATION_API_URL
ARG EXPO_PUBLIC_GEMINI_API_KEY
ARG EXPO_PUBLIC_FIREBASE_API_KEY
ARG EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG EXPO_PUBLIC_FIREBASE_PROJECT_ID
ARG EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG EXPO_PUBLIC_FIREBASE_APP_ID
ARG EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID

ENV ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY \
    ELEVENLABS_VOICE_ID=$ELEVENLABS_VOICE_ID \
    ELEVENLABS_MODEL_ID=$ELEVENLABS_MODEL_ID \
    MEMU_API_KEY=$MEMU_API_KEY \
    MEMU_USER_ID=$MEMU_USER_ID \
    MEMU_AGENT_ID=$MEMU_AGENT_ID \
    MEMU_BASE_URL=$MEMU_BASE_URL \
    SAM_API_URL=$SAM_API_URL \
    SAM_API_KEY=$SAM_API_KEY \
    GEMINI_API_KEY=$GEMINI_API_KEY \
    ANIMATION_API_URL=$ANIMATION_API_URL \
    EXPO_PUBLIC_GEMINI_API_KEY=$EXPO_PUBLIC_GEMINI_API_KEY \
    EXPO_PUBLIC_FIREBASE_API_KEY=$EXPO_PUBLIC_FIREBASE_API_KEY \
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=$EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN \
    EXPO_PUBLIC_FIREBASE_PROJECT_ID=$EXPO_PUBLIC_FIREBASE_PROJECT_ID \
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=$EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET \
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
    EXPO_PUBLIC_FIREBASE_APP_ID=$EXPO_PUBLIC_FIREBASE_APP_ID \
    EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID=$EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# Build the web bundle
RUN npx expo export -p web

# Serve Stage
FROM nginx:alpine

# Copy the built assets from the builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx config if needed (optional, using default for now)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
